root: true
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
  - react
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
settings:
  react:
    version: '16.13'
overrides:
  -
    files: '*.stories.tsx'
    rules:
      react/display-name: off
