name: Deploy Storybook to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Chekcout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ./package.json
      - name: Install Node Dependencies
        run: npm ci
      - name: Build packages
        run: npm run compile
      - name: make public directory
        run: mkdir dist
      - name: Create redirect HTML
        run: echo '<!DOCTYPE html><html><head><meta http-equiv="refresh" content="0; url=/inhouse-components-web/stories-web"></head><body></body></html>' > dist/index.html
      - name: Move adapter dist
        run: mv packages/adapter/dist dist/adapter
      - name: Move stories-web dist
        run: mv packages/stories-web/dist dist/stories-web
      - name: Upload Documents
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  # Deploy the artifact to GitHub pages.
  # This is a separate job so that only actions/deploy-pages has the necessary permissions.
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4

